server:
  port: 5555

spring:
  application:
    name: managergateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: managercore
          uri: http://localhost:8189
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/manager-core
            - JwtAuthFilter
        - id: managerauth
          uri: http://localhost:8188
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/manager-auth
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g